import classNames from "classnames";

import Banner from "../Banner/Banner";

import closeIcon from "../../images/close.svg";
import aboutSm from "../../images/about/about-sm.png";
import aboutSm2 from "../../images/about/about-sm-2x.png";
import aboutSm3 from "../../images/about/about-sm-3x.png";

import aboutMd from "../../images/about/about-md.png";
import aboutMd2 from "../../images/about/about-md-2x.png";
import aboutMd3 from "../../images/about/about-md-3x.png";

import aboutXl from "../../images/about/about-xl.png";
import aboutXl2 from "../../images/about/about-xl-2x.png";
import aboutXl3 from "../../images/about/about-xl-3x.png";

const About = () => {
  return (
    <>
      <div
        id="about"
        className={classNames(
          "mt-[60px] px-[72px] relative",
          "md:mt-[80px] md:px-[88px] md:flex md:flex-wrap md:justify-between",
          "xl:mt-[120px] xl:px-[124px]"
        )}
      >
        <div
          className={classNames(
            "text-left leading-10",
            "md:w-[269px] md:inline-block",
            "xl:w-[538px]"
          )}
        >
          <h2
            className={classNames(
              "text-white text-[40px] font-black font-right-grotesk uppercase leading-10",
              "md:text-6xl leading-[60px] md:w-[269px]",
              "xl:text-[120px] xl:w-[538px] xl:leading-[120px]"
            )}
          >
            a Story that started with{" "}
            <span
              className={classNames(
                "text-my-custom-color text-[40px] font-black font-right-grotesk uppercase leading-10",
                "md:text-6xl leading-[60px] md:w-[269px]",
                "xl:text-[120px] xl:w-[538px] xl:leading-[120px]"
              )}
            >
              one simple{" "}
              <span className="md:hidden">
                <br />
              </span>{" "}
              ape
            </span>
          </h2>
        </div>

        <div
          className={classNames(
            "text-base text-white text-right font-normal font-messina-sans-mono uppercase leading-[19px] mt-[16px]",
            "md:mt-0",
            "xl:text-2xl  xl:leading-[29px]"
          )}
        >
          <p className={classNames("md:w-[275px]", "xl:w-[409px]")}>
            WHO GOT{" "}
            <span className="md:hidden">
              <br />
            </span>{" "}
            FED UP WITH BORING{" "}
            <span className="md:hidden">
              <br />
            </span>{" "}
            AND HYPOCRITIC{" "}
            <span className="md:hidden">
              <br />
            </span>{" "}
            COMMONPLACE THIS IS{" "}
            <span className="md:hidden">
              <br />
            </span>{" "}
            HOW THE IDEA OF <br />
            ESCAPING AND DYNAMIC <br />
            JOURNEY ON THE{" "}
            <span className="sm:hidden">
              <br />
            </span>{" "}
            YACHT
          </p>
        </div>

        <div
          className={classNames(
            "h-24 w-[216px] flex-col justify-start items-center gap-[22px] inline-flex mt-[36px]",
            "md:w-[269px] md:h-[143px] md:mt-[68px] md:gap-[24px]",
            "xl:w-[417px] xl:h-[188px] xl:gap-[36px]  ] xl:mt-[56px]"
          )}
        >
          <div className={classNames("w-6 h-6 relative", "xl:w-9 xl:h-9 ")}>
            <img src={closeIcon} className={classNames("xl:w-9 xl:h-9")} />
          </div>

          <p
            className={classNames(
              "text-center text-white text-xs font-normal font-messina-sans-mono uppercase leading-[14px]",
              "md:text-base md:leading-[19px]",
              "xl:text-2xl xl:leading-[29px]"
            )}
          >
            EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS
            ARE RANDOMLY GENERATED BY USERS
          </p>
        </div>

        <div
          className={classNames(
            "origin-top-center mt-[40px] flex justify-center items-center content-center",
            "md:absolute md:bottom-0 md:right-[88px]",
            "xl:right-[124px]"
          )}
        >
          <img
            srcSet={`${aboutSm} 216w, 
            ${aboutSm2} 432w, 
            ${aboutSm3} 648w, 
            ${aboutMd} 313w, 
            ${aboutMd2} 626w, 
            ${aboutMd3} 939w, 
            ${aboutXl} 492w, 
            ${aboutXl2} 984w
            ${aboutXl3} 1476w
            `}
            sizes="(max-width: 480px) 216px, (max-width: 768px) 313px, 492px"
            src={aboutSm}
            className={classNames(
              "w-[216px] h-[292px]",
              "md:w-[313px] md:h-[422px]",
              "xl:w-[492px] xl:h-[662px]"
            )}
            alt="About Image"
          />
        </div>
      </div>

      <Banner />
    </>
  );
};

export default About;
